### ISSUE TITLE
Event-Nachrichten

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#40]
Beim Versenden einer Event-Nachricht wird der Nachrichtentext nur in das Push-Nachrichten-Popup geschrieben und beim Klick auf das Popup wird im Kalender der App direkt zum Event gesprungen. Längere Nachrichtentexte sind so nicht lesbar.

Stattdessen sollte bei Event-Nachrichten - wie auch bei normalen Freitextnachrichten - ein Klick auf das Popup die Nachrichtenansicht mit dem gesamten Text geöffnet werden und automatisch ein Link auf das Event im Kalender eingefügt werden.

**Comment by Seppo007** [comment]
Verhalten ist nun implementiert, hier eine Übersichtsdarstellung:

![event_action_map](https://cloud.githubusercontent.com/assets/5859802/22796267/169bcb1a-eefa-11e6-93dd-fb17c51d48b7.png)
