### ISSUE TITLE
Open-End-Events

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#41]
Das Ende-Datum eines Events soll in der Datenbank nicht verpflichtend sein. Die Anzeige eines solchen "Open-End-Events" soll in den Apps sinnvoll angepasst werden.

**Comment by cbettinger** [comment]
Server gibt null als Wert für das Feld end aus, falls kein Ende-Datum gesetzt wird. Die App soll solche Events sowohl in der Kalenderübersicht als auch in der Detailansicht wie folgt anzeigen: "Donnerstag, 10. Oktober 2016, ab 15:00". Das Event verhält sich wie ein Eintagesevent, wird also nicht dynamisch umsortiert.

**Comment by Seppo007** [comment]
Statt null, sollte der App 0 übergeben werden, da dies mit der bisherigen Implementierung der annehmenden Methode harmoniert.

[DataMember(Name = "end")]
        private long end;
        public DateTimeOffset End => new DateTimeOffset(JavaDateTimeOffset.AddMilliseconds(end)).LocalDateTime;

**Comment by cbettinger** [comment]
Die einfachste Lösung ist nicht immer die beste Lösung :) Der JSON-Wert null besagt - im Gegensatz zum numerischen Wert 0 - die Abwesenheit eines Wertes. Die Datenhaltung und damit der JSON-Export des Servers ist also semantisch korrekt. Bitte passe die App so an, dass sie damit umgehen kann.

**Comment by cbettinger** [comment]
Ist fertiggestellt, muss aber noch im nächsten Treffen abgenommen werden.

**Comment by Seppo007** [comment]
Android:
![openend_android](https://cloud.githubusercontent.com/assets/5859802/20457986/a532b03e-ae98-11e6-97fe-98c03660e19c.png)
iOS:
![openend_ios](https://cloud.githubusercontent.com/assets/5859802/20457987/a68b3a14-ae98-11e6-98e7-2e2b2e2e8560.png)
Windows Phone:
![openend_wp](https://cloud.githubusercontent.com/assets/5859802/20457988/a83d4b86-ae98-11e6-886a-52ddd75a8089.png)
