### ISSUE TITLE
Mensaplan: Bilder

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#44]
Der Mensaplan soll auch die in der XML-Datei referenzierten Bilder anzeigen. Ist bei einer Speise kein Bild hinterlegt, soll kein Bild (d.h. auch kein Standard-Bild) angezeigt werden.

**Comment by cbettinger** [comment]
Neuen HTTP-Handler am Server: Neuabtastung von Bildern, die als URL übergeben wurden in geringerer Auflösung. Cachen auf Festplatte des Servers.

**Comment by geht** [comment]
Anzeigen der Bilder ist nun fuer alle Plattformen implementiert. Dabei ist das Verhalten auf allen drei Plattformen gleich. Nach dem Parsen der XML werden die Bilder im Hintergrund heruntergeladen. Jedes mal wenn ein Bild fertig heruntergeladen und fuer den View umgewandelt/dekodiert wurde, wird die Tabelle im View invalidiert, um das neue Bild anzuzeigen. Die Bilder werden im lokalen Speicher des Geraetes abgelegt und nur heruntergeladen, wenn sie dort noch nicht vorhanden sind. Analog erfolgt das Dekodieren der Bilder nur, wenn es erforderlich ist.

**Comment by geht** [comment]
Ich habe testweise mal fuer jede Mahlzeit (egal ob sie ein Bild hat oder nicht) das Bild der Gemueselasagne (Aufloesung: 3872x2592 ist doch nicht ganz so riesig, wie ich Erinnerung hatte) geladen. Mit dem aktuellen ImageDecoder ist die OutOfMemoryException zzt. auf keinem der emulierten Geraete mehr reproduzierbar. Getestet habe ich mit dem iPhone 5 Simulator, Windows Phone Simulator (512 MB RAM) und Android 4.2 Simulator (512 MB RAM). Ich werde das Verhalten auch nochmal testen, wenn die Mahlzeiten fuer die ganze Woche geladen (#45)  und angezeigt werden.

![ss 2016-11-13 at 01 12 22](https://cloud.githubusercontent.com/assets/882090/20245571/518cb2c0-a9a4-11e6-807e-3543f3941ce5.jpg)
![ss 2016-11-13 at 01 21 11](https://cloud.githubusercontent.com/assets/882090/20245572/51908a30-a9a4-11e6-9b4d-18d9e00d7b59.jpg)
![ss 2016-11-13 at 12 59 23](https://cloud.githubusercontent.com/assets/882090/20245573/51978e34-a9a4-11e6-9363-f24f4eea11b4.jpg)

**Comment by cbettinger** [comment]
Beim Herunterladen Bilder mit Breite > 1024 auf 1024er Breite skalieren und so lokal speichern.

**Comment by geht** [comment]
Statusupdate:
Das Downscaling müsste plattformspezifisch geschehen, da die eigentlich dafür benötigten Klassen nicht auf allen Plattformen verfügbar sind.
Ich habe das Downscaling mal auf dem WindowsPhone (Emulator mit 512MB RAM) versucht. Das verlagert das OutOfMemory Problem nur vom Decoden ins Downscalen und die App stürzt dann halt dort ab. Auf den anderen Plattformen wird das wohl ähnlich aussehen.

Bei WindowsPhone und Android kann ich noch Anpassungen vornehmen, dass die Bilder gleich mit einer bestimmten Größe decodiert werden (ob und wie das mit iOS geht weiß ich noch nicht), das würde ein bisschen weniger RAM kosten. Das löst das Problem allerdings auch nicht vollständig.

Man müsste das Downscaling tatsächlich irgendwie auslagern, allerdings finde ich es ein wenig "overkill" das ganze jetzt Serverseitig zu implementieren für "eine Hand voll Bilder", bzw. ist es auch irgendwie blöd, wenn solch ein Workaround notwendig wäre. Die übergroßen Bilder sind tatsächlich nur die aus dem /kiosk/img/import/mensa/ Ordner (die "kleinen" kommen aus /upload/bilder/). Werden diese Bilder vom Studiwerk noch irgendwann einmal angepasst? 

Ich habe jetzt vorerst mal eine Art Filter eingebaut, sodass die zu großen Bilder erstmal nicht heruntergeladen werden. Dadurch kommt es jetzt nicht mehr zu dem OutOfMemory-Problem, allerdings werden natürlich auch ein paar weniger Bilder angezeigt (diese Woche gerade 2 Stück).

**Comment by cbettinger** [comment]
Ja, das habe ich erwartet. Und das serverseitige Skalieren halte ich auch für Overkill. Einfluss auf die Bildquellen haben wir nicht, daher kann ich auch nichts dazu sagen, ob die Bilder irgendwann angepasst werden. Vermutlich nicht.

Die Filterung finde ich in Ordnung. Filterst du tatsächlich in Abhängigkeit von der Bildgröße oder in Abhängigkeit von der Bild-URL?

**Comment by geht** [comment]
Zur Zeit in Abhängigkeit der Bildquelle/URL, dadurch spart man sich schon den Download der Dateien (spart Speicherplatz und Kontingent :D). Evtl. ließe sich aber auch einrichten die Abmessung des jeweiligen Bildes vor dem Öffnen abzuchecken (Bei Android gehts ziemlich sicher, Beim WP und iPhone weiß ichs grad nicht sicher). Eine weitere Variante wäre auch nach dem Speicherplatzverbrauch des Bildes zu filtern und beispielsweise Bilder, die größer sind als 1 MiB einfach nicht zu öffnen.

**Comment by cbettinger** [comment]
Die Bildquelle als Filterkriterium zu nehmen ist nicht ganz sauber. Es scheint so, als seien immer die "kiosk"-Bilder so groß, aber das ist nicht verlässlich. Die letzte Variante finde ich eigentlich am besten.

**Comment by geht** [comment]
Bilder die größer sind, als 512 KiB (festgehalten in einer Konstante) werden nun nicht mehr dekodiert.
Weiterhin wird der View jetzt nur noch invalidiert, wenn ein Bild tatsächlich dekodiert wurde, anstatt bei jeder Verarbeitung einer Bild-URL.

**Comment by geht** [comment]
Beim WindowsPhone mit 512 MB RAM (Emulator) tritt immer noch sporadisch eine InsufficientMemoryException auf, die nicht abgefangen werden kann, sodass die App abstürzt.

![ss 2016-11-21 at 05 07 49](https://cloud.githubusercontent.com/assets/882090/20490486/782a89e6-b00e-11e6-9d8e-f1bdf5efb0bc.png)

**Comment by geht** [comment]
Ich habe jetzt mal testweise beim Android mitgeloggt, wie viel Speicher da so alloziert wird für die Bitmaps. Das sind bei den Bildern für die ganze Woche jetzt fast 90 MiB, die da im RAM liegen.

![ss 2016-11-21 at 07 59 24](https://cloud.githubusercontent.com/assets/882090/20496419/63d37d56-b025-11e6-9ccd-aa7614e2e28e.png)
