### ISSUE TITLE
Mensaplan: Wochenplan

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#45]
Der Mensaplan soll nicht nur die Speisen des jeweils aktuellen Tages anzeigen, sondern den Plan der gesamten Woche. Die Navigation zwischen den Tagesplänen soll plattformüblich möglich. Alternativ ist auch die Untereinanderreihung der Tagespläne möglich mit einem automatischen Sprung zum Tagesplan beim Öffnen des Mensaplans (Vgl. Kalender).

**Comment by cbettinger** [comment]
Tagesplane untereinander. Datumsangabe in "Thekenlabel" integrieren. Format: MONTAG, DIENSTAG, ...

**Comment by geht** [comment]
Der Mensaplan zeigt nun die Speisen der gesamten Woche an, dabei wird der Tag nach dem gewünschten Format unter dem Namen der Theke angezeigt. Es wird automatisch der lokalisierte Name des Tages angezeigt, d.h. "Monday, Tuesday, ..." für englische Geräte, "Montag, Dienstag, ..." für deutsche Geräte, usw. (Dies könnte so beibehalten werden oder natürlich auch auf eine feste Sprache gesetzt werden).

Anmerkung: Da der Name der Theken in den Labels der XML komplett in Großbuchstaben eingetragen ist, taucht er auch entsprechend großgeschrieben im Label der App auf. Die Frage ist nun, ob man dementsprechend die Namen der Tage auch komplett großschreiben sollte.

Ein paar Bilder:
![device-2016-11-15-173846](https://cloud.githubusercontent.com/assets/882090/20315288/a8a2ce68-ab5d-11e6-963a-82cf9ee5cc4d.jpg)
![ss 2016-11-15 at 05 23 12](https://cloud.githubusercontent.com/assets/882090/20315291/a8a4ea0e-ab5d-11e6-9554-b5ee081cd71b.jpg)
![ss 2016-11-15 at 05 30 59](https://cloud.githubusercontent.com/assets/882090/20315290/a8a2da70-ab5d-11e6-95fc-91f960b05dcd.jpg)
![ss 2016-11-15 at 05 36 14](https://cloud.githubusercontent.com/assets/882090/20315289/a8a38d8a-ab5d-11e6-9e96-0e2fdbfe96fc.jpg)

**Comment by cbettinger** [comment]
Tageslabel ÜBER Thekenname, Tagesname CamelCase.

**Comment by cbettinger** [comment]
Mensaplan soll auch angezeigt werden können, falls man offline ist und Daten vorliegen.

**Comment by cbettinger** [comment]
Mensa-XML-Datei immer im Hintergrund herunterladen, wenn man in den Mensaplan wechselt. Falls das erfolgreich war, gecachten Mensaplan löschen und neu erzeugen.

**Comment by cbettinger** [comment]
Datumslabel unter Mensaplan-Titel entfernen.

**Comment by geht** [comment]
> Mensa-XML-Datei immer im Hintergrund herunterladen, wenn man in den Mensaplan wechselt. Falls das erfolgreich war, gecachten Mensaplan löschen und neu erzeugen.

Ich bin gerade dabei das Caching für den Mensaplan anzupassen (sodass er beim erfolgreichen Aktualisieren aufgeräumt wird). Soll dann wirklich bei jedem Wechsel auf den Mensaplan nochmal versucht werden zu aktualisieren?

Beispiel: Beim WP wäre das jedes Mal beim Rüberwischen auf den Mensaplan. Das würde dazu führen, dass man bei jedem Wechsel auf den Mensaplan die Meldung bekäme, dass die Daten nicht aktualisiert werden können, wenn man gerade offline ist. Das könnte schnell störend wirken bei Offline-Nutzung. Abgesehen davon wären das, wenn man online ist, jedes Mal ein paar KiB für die XML, die unnötig über die "Leitung" gingen, da sich der Mensaplan ja nicht alle paar Minuten ändert.

Bisher ist die Politik so, dass beim Start der App einmal Kalender und Mensaplan aktualisiert werden. Ansonsten halt dann, wenn man auf "Aktualisieren" drückt. Mit angepasstem Caching vom Mensaplan (inkl. Aufräumen) sollte das von der Häufigkeit eigentlich ausreichen.

**Comment by cbettinger** [comment]
Du hast recht, das war quatsch. Aktualisieren des Mensaplans bei jedem Start ist absolut ausreichend.

**Comment by geht** [comment]
> Tageslabel ÜBER Thekenname, Tagesname CamelCase.

Der Thekenname wird jetzt "übersetzt", sodass jetzt ein CamelCase Name angezeigt wird (Beispiel: "KLEINE KARTE CAFETERIA" wird zu "Cafeteria"). Somit ist jetzt genügend Platz, um den Namen des Tages und der Theke in nur einer Zeile anzuzeigen nach dem Schema "Tag, Theke" (Beispiel: Montag, Theke 1).

> Mensaplan soll auch angezeigt werden können, falls man offline ist und Daten vorliegen.

Das musste nur für Android angepasst werden und wurde entsprechend angepasst.

> Aktualisieren des Mensaplans bei jedem Start ist absolut ausreichend.

Die neue Caching-Politik für den Mensaplan wurde umgesetzt. Bei Start der App wird versucht den aktuellen Mensaplan herunterzuladen. Ist dies erfolgreich, so werden die neuen Daten gecached (alte Daten werden überschrieben) und angezeigt. Andernfalls werden die gecachten Daten geladen und angezeigt. Das Verhalten bei Druck auf den jeweiligen "Aktualisieren"-Knopf ist analog.

> Datumslabel unter Mensaplan-Titel entfernen.

Das war ja nur beim WindowsPhone der Fall und wurde dementsprechend angepasst.

Ausführlichere Informationen sind im folgenden commit: 68177402e2db5385c370dfb1d11ab7bd151a28ff

Bilder:
![ss 2016-11-20 at 01 01 10](https://cloud.githubusercontent.com/assets/882090/20462889/09e5999e-af28-11e6-9f59-5c2648a01c66.jpg)
![screenshot_20161120-130349](https://cloud.githubusercontent.com/assets/882090/20462890/0d1cb58e-af28-11e6-94c3-eb49a58e191b.png)

**Comment by cbettinger** [comment]
In Kontextmenü zwei Einträge:
- Tagesplan
- Wochenplan

Beim Wechsel zum Hauptmenüpunkt Mensaplan wird immer der Tagesplan geladen.

Im Tagesplan werden alle Bilder angezeigt. Im Wochenplan gar keine Bilder.

**Comment by geht** [comment]
Der neue Mensaplan ist jetzt implementiert für WindowsPhone.

Tagesansicht mit Bildern:
![ss 2016-11-24 at 03 30 43](https://cloud.githubusercontent.com/assets/882090/20601988/ae3e557c-b25b-11e6-846e-505d3410f9ce.jpg)

Kontextmenü:
![ss 2016-11-24 at 03 31 35](https://cloud.githubusercontent.com/assets/882090/20602014/c647c374-b25b-11e6-90d5-1ed80d45a5ea.png)

Wochenansicht ohne Bilder:
![ss 2016-11-24 at 03 32 14](https://cloud.githubusercontent.com/assets/882090/20602040/de4ec440-b25b-11e6-8172-4311c3946e16.png)

**Comment by cbettinger** [comment]
Sieht gut aus.

**Comment by geht** [comment]
Implementierung für Android.

Tagesansicht mit Bildern:
![screenshot_20161124-160407](https://cloud.githubusercontent.com/assets/882090/20603175/a473c7a2-b260-11e6-98e3-f8ad2a3702fd.png)

Kontextmenü:
![screenshot_20161124-160415](https://cloud.githubusercontent.com/assets/882090/20603184/b00e107c-b260-11e6-8595-2f6dcd155b0c.png)

Wochenansicht ohne Bilder:
![screenshot_20161124-160434](https://cloud.githubusercontent.com/assets/882090/20603197/be602fc0-b260-11e6-8544-4e255a1772c8.png)

**Comment by geht** [comment]
> Statt "wochenplan" könnte man auch den String "diese woche" verwenden. Das wäre dann einheitlicher.

Ist angepasst.
![ss 2016-11-24 at 04 14 45](https://cloud.githubusercontent.com/assets/882090/20603406/af72fef6-b261-11e6-8fc0-96ee620b1abb.png)
![screenshot_20161124-161707](https://cloud.githubusercontent.com/assets/882090/20603411/b2a038dc-b261-11e6-8f9c-a27909e6c43c.png)

**Comment by geht** [comment]
Implementierung für iOS.

Tagesansicht mit Bildern:
![ss 2016-11-24 at 04 39 18](https://cloud.githubusercontent.com/assets/882090/20604277/e4577328-b265-11e6-94b7-a0e79576b63b.jpg)

Kontextmenü:
![ss 2016-11-24 at 04 40 04](https://cloud.githubusercontent.com/assets/882090/20604285/ec83f0d0-b265-11e6-93a5-dafbc303ae76.jpg)

Wochenansicht ohne Bilder:
![ss 2016-11-24 at 04 40 31](https://cloud.githubusercontent.com/assets/882090/20604287/f12775f8-b265-11e6-85bf-ced533b7e96e.png)

**Comment by cbettinger** [comment]
In der iOS-Variante wird noch der alte String verwendet. Bitte überall "Heute" bzw. "Diese Woche" einsetzen. Bitte denke daran, alle Strings in die strings.txt auszulagern.

**Comment by geht** [comment]
> In der iOS-Variante wird noch der alte String verwendet. Bitte überall "Heute" bzw. "Diese Woche" einsetzen. Bitte denke daran, alle Strings in die Strings.txt auszulagern.

Das hatte ich schon in die Strings.txt eingetragen, ich überprüf das noch mal.

**Comment by geht** [comment]
Ich hatte scheinbar nur einen alten Stand der automatisch generierten String Resourcen. Nach erneutem Ausführen des StringResources-Tools taucht auch hier der richtige Text auf.

![ss 2016-11-25 at 10 52 33](https://cloud.githubusercontent.com/assets/882090/20621176/975e29a2-b2fd-11e6-9975-e13f47280c10.jpg)

**Comment by geht** [comment]
Memo an mich selbst: Der Wochenplan soll nach aufsteigendem Datum sortiert sein, auch wenn die Sortierung der Daten in der XML anders aussehen.

**Comment by geht** [comment]
> Der Wochenplan soll nach aufsteigendem Datum sortiert sein, auch wenn die Sortierung der Daten in der XML anders aussehen.

Der Wochenplan wird jetzt korrekt sortiert.

**Comment by geht** [comment]
Der Tagesplan zeigt jetzt die Mahlzeiten des nächst verfügbaren Tages an, falls der jeweilige Tag keinen Eintrag in der XML hat (das ist der Fall, wenn die Mensa an dem Tag geschlossen ist).
Führt man die App beispielsweise am Wochenende aus, so werden die Mahlzeiten vom kommenden Montag angezeigt (falls die Mensa da geöffnet hat).
