### ISSUE TITLE
Kalender: Layout-Problem bei Events mit gesetztem "recommended"-Attribut

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#46]
Falls bei einem Event das Attribut "recommended" gesetzt ist, wird im Kalender die Information "Basis-Info" eingeblendet. Besteht der Kalendereintrag nur aus zwei Zeilen (z.B. weil das Attribut "location" nicht gesetzt ist), überlappen die Labels mit dem "Basis-Info"-Hinweis (siehe Anhang).

In diesem Fall soll der Kalendereintrag vertikal so vergrößert werden, dass der weiterhin in unteren rechten Ecke positionierte Hinweis nicht mehr überlappen kann.

![2016-09-14 12 04 15](https://cloud.githubusercontent.com/assets/18167176/19764212/1a97beb4-9c42-11e6-91f7-d4bf59b5195e.png)

**Comment by Seppo007** [comment]
![recommendation_android](https://cloud.githubusercontent.com/assets/5859802/20457999/db7b1e92-ae98-11e6-8b11-746d83a390b0.png)

**Comment by cbettinger** [comment]
Ist bzw. war das tatsächlich ein Bug, der sich ausschließlich in der Android-Version niederschlägt?

**Comment by Seppo007** [comment]
Ja, wegen des Layoutings der Android Version.
iOS hatte auch ein Problem, siehe Issue #56.
WP hatte es bereits so implementiert, dass keine Überdeckung stattfand.

**Comment by cbettinger** [comment]
Für WP noch abzunehmen.

**Comment by Seppo007** [comment]
Gesetztes Recommended-Attribut ohne dass ein Veranstaltungsort gesetzt ist in WP:

![image](https://cloud.githubusercontent.com/assets/5859802/20575808/390c2a68-b1bb-11e6-936f-557fc679d8f6.png)
