### ISSUE TITLE
Kalender: Umsortieren von Mehrtagesevents

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#47]
Die Kalendereinträge sollen bei jedem Aufruf des Kalenders dynamisch umsortiert werden.

Events, die sich über mehrere Tage erstrecken (Datumsanteil Start-Datum != Datumsanteil End-Datum) und die zum aktuellen Zeitpunkt "laufen" (Start-Datum <= Jetzt <= End-Datum) sollen nicht immer im Hinblick auf das Start-Datum einsortiert werden, sondern vor die Events des aktuellen Tages (falls es welche gibt) bzw. vor die jeweils nächsten Events (falls es keine Events am aktuellen Tag gibt) einsortiert werden.

**Comment by Seppo007** [comment]
Android nutzt eine andere Art des Zugriffs auf das CalendarViewmodel, daher müssen für Android noch Anpassungen vorgenommen werden

**Comment by cbettinger** [comment]
Neues Feld in lokalen Event-Objekten mit modifiziertem BeginDate. Dieses Feld wird für die Sortierung betrachtet. Für die Ausgabe wird das BeginDate-Feld weiterhin genutzt.

**Comment by cbettinger** [comment]
Es sollen nicht nur mehrtätige Wochenaufgaben, sondern alle mehrtägige Events umsortiert werden.

**Comment by cbettinger** [comment]
Ist fertiggestellt, muss aber noch im nächsten Treffen abgenommen werden.

**Comment by Seppo007** [comment]
Android:
![mehrtagesevents_android](https://cloud.githubusercontent.com/assets/5859802/20457992/c65233fc-ae98-11e6-8659-0e8223b99f25.png)
iOS:
![mehrtagesevents_ios](https://cloud.githubusercontent.com/assets/5859802/20457994/c7bde326-ae98-11e6-9611-f3706e6b1564.png)
Windows Phone:
![mehrtagesevents_wp](https://cloud.githubusercontent.com/assets/5859802/20457995/c921200c-ae98-11e6-8557-77cfaa2fab95.png)
