### ISSUE TITLE
Exception beim Start der Android-App mit Android Version < 5

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#50]
![screenshot 2016-11-03 15 22 17](https://cloud.githubusercontent.com/assets/18167176/20140307/ba3354ea-a68a-11e6-92d5-ff9d3dd17584.png)

**Comment by Seppo007** [comment]
Nutzung von Methoden der Support Library lässt die App starten, jedoch gibt es Probleme beim Inflaten der Events.axml für die Events im Kalender.

Die Exception lautet dabei wie folgt:
Android.Views.InflateException: Binary XML file line #1: Error inflating class <unknown>

Bisher hat intensive Recherche im Netz zu keiner Lösung geführt, auch das Testen mit Android 4.4 scheiterte letztendlich an dem Aufruf.

Da aktuell die Nutzer mit 4.4 noch einen prozentualen Anteil an den Gesamtnutzern von 25% ausmachen, sollte auf diese Gruppe nicht verzichtet und der bug definitiv behoben werden.
(https://developer.android.com/about/dashboards/index.html)

**Comment by Seppo007** [comment]
![image](https://cloud.githubusercontent.com/assets/5859802/20457159/414d7bca-ae85-11e6-84e0-faf8754b00cb.png)

**Comment by Seppo007** [comment]
> 11-20 11:54:28.284 I/MonoDroid( 1833): UNHANDLED EXCEPTION:
> 
> 11-20 11:54:28.324 I/MonoDroid( 1833): Android.Views.InflateException: Binary XML file line #1: Error inflating class <unknown> 
> 											---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. 
> 											---> Android.Content.Res.Resources+NotFoundException: File res/drawable/eventviewbackground.xml from drawable resource ID #0x7f02007b 
> 											---> Org.XmlPull.V1.XmlPullParserException: Binary XML file line #1: <item> tag requires a 'drawable' attribute or child tag defining a drawable
> 11-20 11:54:28.324 I/MonoDroid( 1833):    --- End of inner exception stack trace ---
> 11-20 11:54:28.334 I/MonoDroid( 1833):    --- End of inner exception stack trace ---
> 11-20 11:54:28.334 I/MonoDroid( 1833):    --- End of inner exception stack trace ---
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00085] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11283 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00031] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:350 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root) [0x0003f] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.LayoutInflater.cs:619 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at App100Tage.ADroid.Data.Adapter.EventArrayAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00028] in H:\GitWin8\HundertTage\App\App100Tage.Android\Data\Adapter\EventArrayAdapter.cs:47 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.BaseAdapter.cs:443 
> 11-20 11:54:28.334 I/MonoDroid( 1833):   at (wrapper dynamic-method) System.Object:6a4b8a5a-a762-4bb1-a1f1-8331937cc9ba (intptr,intptr,int,intptr,intptr)
> 11-20 11:54:28.334 I/MonoDroid( 1833):   --- End of managed Android.Views.InflateException stack trace ---
> 
> 11-20 11:54:28.334 I/MonoDroid( 1833): android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.createView(LayoutInflater.java:621)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at md59f6de616b557cf076d8812ef2fd742d2.EventArrayAdapter.n_getView(Native Method)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at md59f6de616b557cf076d8812ef2fd742d2.EventArrayAdapter.getView(EventArrayAdapter.java:45)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at se.emilsjolander.stickylistheaders.AdapterWrapper.getView(AdapterWrapper.java:164)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at se.emilsjolander.stickylistheaders.AdapterWrapper.getView(AdapterWrapper.java:26)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.AbsListView.obtainView(AbsListView.java:2263)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.ListView.fillDown(ListView.java:691)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.ListView.fillFromTop(ListView.java:752)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.ListView.layoutChildren(ListView.java:1616)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at se.emilsjolander.stickylistheaders.WrapperViewList.layoutChildren(WrapperViewList.java:193)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.AbsListView.onLayout(AbsListView.java:2091)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onLayout(StickyListHeadersListView.java:265)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.layout(View.java:14817)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.os.Handler.handleCallback(Handler.java:733)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.os.Looper.loop(Looper.java:136)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at java.lang.reflect.Method.invokeNative(Native Method)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at java.lang.reflect.Method.invoke(Method.java:515)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at dalvik.system.NativeStart.main(Native Method)
> 
> 11-20 11:54:28.334 I/MonoDroid( 1833): Caused by: java.lang.reflect.InvocationTargetException
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at java.lang.reflect.Constructor.constructNative(Native Method)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.LayoutInflater.createView(LayoutInflater.java:595)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	... 59 more
> 
> 11-20 11:54:28.334 I/MonoDroid( 1833): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/eventviewbackground.xml from drawable resource ID #0x7f02007b
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.content.res.Resources.loadDrawable(Resources.java:2101)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.View.<init>(View.java:3554)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.view.ViewGroup.<init>(ViewGroup.java:470)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.LinearLayout.<init>(LinearLayout.java:176)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.widget.LinearLayout.<init>(LinearLayout.java:172)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	... 62 more
> 
> 11-20 11:54:28.334 I/MonoDroid( 1833): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: <item> tag requires a 'drawable' attribute or child tag defining a drawable
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.content.res.Resources.loadDrawable(Resources.java:2097)
> 11-20 11:54:28.334 I/MonoDroid( 1833): 	... 67 more
> 
> 11-20 11:54:28.424 D/Mono    ( 1833): DllImport searching in: '__Internal' ('(null)').
> 11-20 11:54:28.424 D/Mono    ( 1833): Searching for 'java_interop_jnienv_throw'.
> 11-20 11:54:28.424 D/Mono    ( 1833): Probing 'java_interop_jnienv_throw'.
> 11-20 11:54:28.424 D/Mono    ( 1833): Found as 'java_interop_jnienv_throw'.
> 11-20 11:54:28.434 D/dalvikvm( 1833): GC_CONCURRENT freed 709K, 12% free 5929K/6708K, paused 14ms+1ms, total 76ms

**Comment by Seppo007** [comment]
Das Problem wurde identifiziert:

Die Layout-Datei "EventViewBackground.xml" war syntaktisch falsch aufgebaut, ab Android 5.0 wurde dies scheinbar so angepasst, dass der Fehler automatisch korrigiert wurde.

Die Exception wies einige Caused-By-Lines auf, wovon eine wie folgt lautete:

11-20 11:54:28.334 I/MonoDroid( 1833): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: <item> tag requires a 'drawable' attribute or child tag defining a drawable
11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
11-20 11:54:28.334 I/MonoDroid( 1833): 	at android.content.res.Resources.loadDrawable(Resources.java:2097)
11-20 11:54:28.334 I/MonoDroid( 1833): 	... 67 more


Das EventViewBackground-Layout wurde dahingehend syntaktisch korrekt angepasst.
