### ISSUE TITLE
StudIP-Events: ganztägige Events führen zu ParsingFehler

### ISSUE THREAD

**Issue by Seppo007** [HundertTage/App#53]
Das Erstellen von ganztägigen Events im StudIP-Kalender führt beim Import des Kalenders in der App dazu, dass gar keine Events aus dem StudIP-Kalender mehr angezeigt werden.

Es scheint als gäbe es Probleme beim Importieren der hinterlegten Datumsangaben / Uhrzeiten des ganztägigen Events.

**Comment by Seppo007** [comment]
![image](https://cloud.githubusercontent.com/assets/5859802/20458339/6a2ed0bc-aea2-11e6-94bb-94fe2d3343a0.png)

**Comment by Seppo007** [comment]
![image](https://cloud.githubusercontent.com/assets/5859802/20458718/58378408-aeac-11e6-89e0-d5e81d981743.png)

**Comment by cbettinger** [comment]
Bei Ganztagesevents in der Anzeige Uhrzeit weglassen, d.h. im Beispiel:
Freitag, 18. November

**Comment by Seppo007** [comment]
So werden ab jetzt ganztägige Events dargestellt:

![image](https://cloud.githubusercontent.com/assets/5859802/20576730/6b4e9dea-b1bf-11e6-8b63-a45316456009.png)

![image](https://cloud.githubusercontent.com/assets/5859802/20576847/e5043a78-b1bf-11e6-9391-d3ab85ca1396.png)


Ganztägige Events sind dadurch gekennzeichnet, dass

a) der Anfangstag und der Endttag eines Ereignisses übereinstimmen
b) die Startzeit 00:00:00 und die Endzeit 23:59:59 beträgt
