### ISSUE TITLE
Exception beim Öffnen einer Wochenaufgabe

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#54]
Tritt bei einem Nexus 10-Tablet beim Öffnen einer Wochenaufgabe im Kalender aus.

![screenshot 2016-11-17 14 09 53](https://cloud.githubusercontent.com/assets/18167176/20390513/9cb633ba-accf-11e6-9757-b72e2916f4cd.png)

**Comment by Seppo007** [comment]
Wurde behoben. Der Fehler lag in der Verwendung von TextView.setTextAppearance(int resID). Diese Art des Methodenaufrufs gab es vor API23 nicht, die zuvor verwendet Methode TextView.setTextAppearance(Context ctx, int resID) ist nun deprecated.

Daher wurde die Android-Support-Library mit der TextViewCompat-Klasse verwendet.
