### ISSUE TITLE
iOS-Layouting: Zu langer Location-String verdeckt Recommendation-Label

### ISSUE THREAD

**Issue by Seppo007** [HundertTage/App#56]
Ein zu langer Location-String wie z.B. Fachschaftsraum Informatik verdeckt, falls es dem Event zugewiesen wurde, das Recommendation-Label.

![image](https://cloud.githubusercontent.com/assets/5859802/20457745/2e2c5ce8-ae92-11e6-8e0c-7bdd36de9668.png)

**Comment by Seppo007** [comment]
Constraints angepasst, sollte später aber evtl. programmatisch gelöst werden, je nachdem wie aufwendig es ist, dies für ein Auto-Layout wie es verwendet wird zu realisieren

![bildschirmfoto 2016-11-19 um 18 36 17](https://cloud.githubusercontent.com/assets/5859802/20457826/27c0a5ba-ae94-11e6-85e2-ed23f47a154b.png)
![bildschirmfoto 2016-11-19 um 20 05 56](https://cloud.githubusercontent.com/assets/5859802/20457827/29c0fb44-ae94-11e6-9e84-f09214767d21.png)

**Comment by Seppo007** [comment]
Programmatisches behandeln von Constraints ermöglicht das richtige Umbrechen von Ortsangaben bei nicht gesetztem Recommended-Attribut:

![umbruch](https://cloud.githubusercontent.com/assets/5859802/20899329/45707ac0-bb2a-11e6-9b0f-e7f6b99b0d11.png)

**Comment by cbettinger** [comment]
Super!
