### ISSUE TITLE
Starter-Icon überprüfen

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#60]
Bitte prüft mal nach, ob auf allen drei Plattformen das gleiche Icon zum Starten der App eingesetzt wird. Ich bin mir da nicht ganz sicher.

1. Das Icon sollte in allen drei App-Varianten die gleichen Abmessungen besitzen. Die Abmessungen sollten so groß sein, dass auch bei Geräten mit hoher Pixeldichte (z.B. 400 dpi) das Logo nicht pixelig wirkt. Hier eine PNG-Grafik mit 1024er Kantenlänge:
![iconbig_1024](https://cloud.githubusercontent.com/assets/18167176/20483768/1c1eb920-aff4-11e6-89d2-fa2fb955da2c.png)

Solltet ihr eine noch größere Datei benötigen, gebt mir bitte Bescheid.

2. Es gibt eine Version des Logos mit und eine Version ohne horizontale Striche unterhalb und überhalb des Logos. Bitte prüft, ob alle Apps die gleiche Version (mit Strichen) einsetzen.

3. Da unter iOS die Ecken des Starter-Icons abgerundet werden, ist der Whitespace ober-/unterhalb der horizontalen Striche etwas zu gering - das Logo wirkt gequetscht. Evtl. muss hier eine Variante des Logos mit mehr explizit eingefügtem Whitespace an allen vier Seiten erstellt werden.
![2016-11-21 14 07 21](https://cloud.githubusercontent.com/assets/18167176/20483812/6830d2ee-aff4-11e6-9080-36512a3e2166.png)

**Comment by Seppo007** [comment]
Aktuelle Abmessungen der Icons:

- Windows Phone: 100 x 100 Pixel
- Android: 512 x 512 Pixel
- iOS: 1200 x 1200 / 800 x 800 & 400 x 400

Ich denke es macht, mit Hinblick auf hochauflösende Geräte, überall 512er / bzw. 1024er Logo zu benutzen.

**Comment by cbettinger** [comment]
Ja, das denke ich auch. Wenn alle Plattformen 1024er-Logos erlauben, dann nutzt dieses.

**Comment by Seppo007** [comment]
Googles Empfehlungen für Android:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html

**Comment by cbettinger** [comment]
Überraschend knauserig :) Bitte schlage die entsprechenden Empfehlungen oder Vorgaben auch für die anderen Plattformen nach und setze das entsprechend um.

**Comment by cbettinger** [comment]
iOS ok, WP ok, für Android: 1024er + entsprechend kleiner skalierte Varianten (TODO)

**Comment by Seppo007** [comment]
[LogoiPhone_new-60x60.pdf](https://github.com/HundertTage/App/files/631625/LogoiPhone_new-60x60.pdf)
[LogoiPhone_new-76x76.pdf](https://github.com/HundertTage/App/files/631626/LogoiPhone_new-76x76.pdf)
[LogoiPhone_new-400x400.pdf](https://github.com/HundertTage/App/files/631627/LogoiPhone_new-400x400.pdf)
[LogoiPhone_new-29x29.pdf](https://github.com/HundertTage/App/files/631628/LogoiPhone_new-29x29.pdf)
[LogoiPhone_new-40x40.pdf](https://github.com/HundertTage/App/files/631629/LogoiPhone_new-40x40.pdf)

Dies wären die aktualisierten Logos, allerdings nimmt iOS diese nicht an, da sie quadratisch sein müssen. Daher sollte darüber nachgedacht werden, ob für iOS der Einfachheit halber nicht das Logo ohne horizontale Striche verwendet werden sollte.

Die Entscheidung für das Logo mit horizontalen Strichen in iOS würde dazu führen, dass das Logo im Quadrat gestaucht / so verkleinert werden müsste, dass die äußeren Blank-Screens größer und quadratisch ausfallen und somit das Logo anders als auf den anderen Plattformen aussehen würde.

**Comment by cbettinger** [comment]
Hier eine Version des Logos ohne Balken mit 2560er-Abmessung. Was haltet ihr davon, in allen drei Apps die Version ohne Balken zu verwenden?

<img width="1280" alt="logov3 1" src="https://cloud.githubusercontent.com/assets/18167176/20918487/90bec58c-bb97-11e6-839c-a157b9989e12.png">

**Comment by geht** [comment]
App-Icons sind ja schon durch die vorgegebenen Abmessungen recht stark begrenzt, durch die horizontalen Balken wirkt das Icon noch eingeschränkter. Dieser Effekt ist beim iPhone am deutlichsten zu sehen, da hier die Ecken noch zusätzlich abgerundet sind. Das Icon ohne Balken würde meiner Meinung nach ein saubereres Gesamtbild abgeben.

**Comment by Seppo007** [comment]
Also ich finde das Icon mit den Balken deutlich attraktiver und ansprechender, aber aufgrund der Art und Weise, wie die verschiedenen Systeme die Icons formatieren würde ich auch auf die balkenlose Darstellung umsteigen.

Ich passe das dementsprechend am WE noch an.

**Comment by Seppo007** [comment]
Die Icons wurden auf allen 3 Plattformen ersetzt und angepasst.

- iOS generiert aus bereitgestellten Vektorgrafiken innerhalb von PDFs die benötigten PNGs automatisch.
- Für Android wurden die Launcher-Icons gemäß Empfehlung von Google angepasst und eingepflegt (https://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html / http://iconhandbook.co.uk/reference/chart/android/)
- Für Windows Phone wurden die bisherigen Auflösungen übernommen und die Bilddateien angepasst

![logoios](https://cloud.githubusercontent.com/assets/5859802/21075947/7ee94eb4-bf1f-11e6-90c3-4a419da420a9.png)
![logoandroid](https://cloud.githubusercontent.com/assets/5859802/21075948/82bf2b76-bf1f-11e6-967a-0dc94383e156.png)
![logowp](https://cloud.githubusercontent.com/assets/5859802/21075949/85122572-bf1f-11e6-8032-d873ab59fa14.png)

**Comment by Seppo007** [comment]
Bedauerlicherweise ist mir ein Fehler unterlaufen. 
Ich habe die letzten Änderungen bezüglich des neuen Logos zwar durchgezogen, jedoch nicht in den develop gemerged.

Somit sind die neuen Logos ohne Balken zur Zeit nicht im Release 3.1 enthalten und werden daher leider erst mit dem nächsten Release auf den Endgeräten der Studierenden bereitstehen.
