### ISSUE TITLE
Automatisches Aktualisieren von Events

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#61]
Wann werden Events neu vom Server heruntergeladen?

Falls dies bei jedem Start der Anwendung erfolgt, dann wäre der Push-Nachrichtentyp "UPDATE" überflüssig, oder? Falls ja, dann kann dieser Nachrichtentyp entfernt werden.

Falls die Events nicht automatisch (d.h. bei jedem Start der Anwendung) aktualisiert werden, gibt es etwas das dagegen spricht? Falls nein, bitte umsetzen.

**Comment by Seppo007** [comment]
Also ich habe jetzt mal alle drei App-Varianten nochmal genau dahingehend überprüft und in der WP-Variante noch ein paar Fehler ausgemerzt bezüglich des Update-Verhaltens.

Windows Phone, Android und iOS sind zur Zeit so implementiert, dass sie NICHT beim Start immer den Kalender updaten. Der Download der Events vom Server wird nur dann ausgeführt wenn entweder die App neu auf dem Gerät installiert wurde und keine Daten im Cache liegen, per Push-Notification der Aktualisierungsprozess angestoßen wurde, oder manuell der Aktualisierungs-Button gedrückt wurde.

Ansonsten werden stets die Event-Einträge aus dem Cache genutzt.

Nun stellt sich daher erneut die Frage was hier eher gewünscht ist. Stetiges Aktualisieren beim Starten der App, oder aktualisieren nur bei Push-Nachrichten und manueller Klick auf den Aktualisieren-Button.

**Comment by cbettinger** [comment]
Dann lassen wir es so wie es ist.

**Comment by Seppo007** [comment]
Android fragt nun doch wieder bei jedem Start erneut die Events ab.
Ich werde das noch einmal genau überprüfen und entsprechende Änderungen vornehmen.
