### ISSUE TITLE
Layout-Problem ("Basis-Info") für ganztätige Events ohne Ort

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#67]

**Comment by Seppo007** [comment]
Problem wurde mittels entsprechender Constraints gelöst

**Zusammenschnitt:**
![basisinfo](https://cloud.githubusercontent.com/assets/5859802/20899258/0392fab0-bb2a-11e6-9380-7e8ea3ff68f8.png)

**Comment by Seppo007** [comment]
Darüber hinaus konnten Verbessungen für Issue #56 erreicht werden

**Comment by cbettinger** [comment]
Klappt das auch, wenn das recommended-Attribut gesetzt ist und der Orts-String sehr lang ist?

**Comment by Seppo007** [comment]
Vielen Dank für die Anmerkung, habe tatsächlich noch einen Fehler in meinem Code gefunden, sodass ich die Constraints gar nicht mehr reaktiviert hatte und somit auch bei gesetztem Constraint fortan bei langer Ortsangabe diese verdekckt wurde.

Ist nun angepasst
