### ISSUE TITLE
Busfahrplan

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#69]
Neuer Hauptmenüpunkt "Busfahrplan". Wie auf den Info-Displays am Campus sollen die nächsten Abfahrten (die nächsten X Abfahrten oder die Abfahrten in den nächsten x Minuten) von Bussen vom Hauptcampus Schneidershof aufgelistet werden.

**Comment by geht** [comment]
Statusupdate:

Die Implementierung des plattformübergreifenden Teils (PCL) steht soweit. Busfahrplandaten werden für die Haltestellen "Hochschule Trier" und "Bitburger Straße" heruntergeladen, geparst und sortiert.

Für WindowsPhone habe ich jetzt auch schon den View umgesetzt. Die App hat ein neues Panoramaelement (zwischen Mensaplan und Stadtplan) zur Anzeige der Busfahrten. Bei der Darstellung habe ich mich an der FSI-App orientiert, dementsprechend werden Bestimmungsort, Linie, Abfahrtszeit und Verspätung in Minuten angezeigt.

![ss 2016-12-09 at 04 41 04](https://cloud.githubusercontent.com/assets/882090/21054649/cc957a9e-be2e-11e6-8fa8-bc886f8c15dc.png)
![ss 2016-12-09 at 04 41 34](https://cloud.githubusercontent.com/assets/882090/21054654/cfa6a5fa-be2e-11e6-96f5-a2e1e683a349.png)

**Comment by cbettinger** [comment]
Sieht gut aus. Bitte vor die Liniennummern den Präfix "Linie " setzen.

Verstehe ich das richtig, dass die Busse in beide Richtungen (In die Innenstadt bzw. in Richtung Bitburg) angezeigt werden?

**Comment by geht** [comment]
> Bitte vor die Liniennummern den Präfix "Linie " setzen.

wird gemacht.



> Verstehe ich das richtig, dass die Busse in beide Richtungen (In die Innenstadt bzw. in Richtung Bitburg) angezeigt werden?

Korrekt, der WebService liefert zu der angefragten Haltestelle die Busse in alle Richtungen.

**Comment by geht** [comment]
> Bitte vor die Liniennummern den Präfix "Linie " setzen.
> wird gemacht.

wurde gemacht :D

![ss 2016-12-12 at 05 07 27](https://cloud.githubusercontent.com/assets/882090/21106340/05792688-c08e-11e6-9e58-fa282b3b34d3.png)

**Comment by geht** [comment]
Der View für Android ist jetzt implementiert:

![screenshot_20161213-094807](https://cloud.githubusercontent.com/assets/882090/21133571/bab5ab4e-c119-11e6-9f87-97c7a4c106c9.png)

![screenshot_20161213-094812](https://cloud.githubusercontent.com/assets/882090/21133579/c25bde68-c119-11e6-9300-a7d6efb5e91d.png)

**Comment by geht** [comment]
Und hier der View für iOS.
Man beachte, uns fehlt noch ein passendes Icon für den Busplan unten in der Navigationsleiste.

![simulator screen shot 13 12 2016 10 31 32](https://cloud.githubusercontent.com/assets/882090/21134745/89ea6030-c11f-11e6-8467-7d2a80ce496f.png)

**Comment by cbettinger** [comment]
Bitte benenne den Hauptmenüpunkt von "Busse" in "Busfahrplan" um. Das sieht zwischen "Mensaplan" und "Stadtplan" einfach passender aus.

**Comment by geht** [comment]
> Bitte benenne den Hauptmenüpunkt von "Busse" in "Busfahrplan" um.

erledigt.

![wp_ss_20161213_0003](https://cloud.githubusercontent.com/assets/882090/21137208/168e93c2-c129-11e6-8845-8d05d738e2e1.png)

![screenshot_20161213-113940](https://cloud.githubusercontent.com/assets/882090/21137214/1a836afc-c129-11e6-8bae-af24ef73a86c.png)

![simulator screen shot 13 12 2016 11 35 54](https://cloud.githubusercontent.com/assets/882090/21137221/1d26982e-c129-11e6-9f72-7bc0028c5292.png)

**Comment by cbettinger** [comment]
Bitte auf offizielle Schnittstelle der VRT nutzen.

**Comment by cbettinger** [comment]
Busfahrplan-Icon

**Comment by geht** [comment]
Farbe wurde angepasst:

![ss 2016-12-20 at 12 34 38](https://cloud.githubusercontent.com/assets/882090/21349427/2cfb397e-c6b2-11e6-922a-0fcb3b804e01.png)
![ss 2016-12-20 at 12 38 10](https://cloud.githubusercontent.com/assets/882090/21349430/2e8b8ffa-c6b2-11e6-8fbb-ba0e17f6421b.png)
![ss 2016-12-20 at 12 43 49](https://cloud.githubusercontent.com/assets/882090/21349431/2fb6c07a-c6b2-11e6-8c93-fcacfc275a74.png)

**Comment by geht** [comment]
> Busfahrplan-Icon

Neues Icon ist eingebaut:

![ss 2016-12-20 at 01 05 47](https://cloud.githubusercontent.com/assets/882090/21350039/889517ac-c6b5-11e6-8965-46705af59875.png)

**Comment by cbettinger** [comment]
Sehr schön!

**Comment by cbettinger** [comment]
TODO:
* Umstellen auf offizielle VRT-Schnittstelle
* Auf oberste Ebene unterscheiden zwischen "In Richtung Innenstadt" und "In Richtung Bitburg".

**Comment by cbettinger** [comment]
"In Richtung Innenstadt" soll zuoberst angezeigt werden.

**Comment by geht** [comment]
> Umstellen auf offizielle VRT-Schnittstelle

Die bisherige Funktionalität ist jetzt umgestellt auf die Trias-Schnittstelle vom VRN.
Für die Haltestelle(n) an der Hochschule wird hier mitgeliefert, von welchem Steig die Busse jeweils abfahren.

Das sieht beispielsweise so aus:

![](http://puu.sh/tixPl/fdfead1ca8.png)

![](http://puu.sh/tixWq/06200f148b.png)

Der Umbau auf die Richtungen erfolgt noch.

**Comment by cbettinger** [comment]
* NICHT nach Richtung sortieren
* Kategorisierung nach Bussteig rausnehmen, d.h. eine Liste für alle Bussteige
* Bussteig in neues Label unter Linie aufnehmen (Schriftgröße wie Linie)
* Zuordnung Bussteig/Richtung prüfen
* Verspätungszeit ergänzen (falls möglich), sonst Label rausschmeißen

**Comment by geht** [comment]
Die Gruppierung ist entfernt, die Liste ist nun flach und nach Abfahrt sortiert.
Die Haltestelle wurde als Label unter der Linie aufgenommen.
Das Label für die Verspätung wird jetzt nur noch angezeigt, wenn der Bus Verspätung hat.
Des Weiteren habe ich die Daten, die angezeigt werden ein wenig aufgeräumt.
Für Standorte innerhalb Trier (Bsp.: "Trier, Hochschule Trier") wird das Präfix "Trier, " weggelassen.
Für Standorte ausserhalb Trier (Bsp.: "Bitburg, ZOB") wird nur der Ort angezeigt.

Windows Phone
![](https://puu.sh/tkTvd/42d9d95c2d.png)

Android
![](https://puu.sh/tkTrU/5a2b23ed75.png)

iPhone
![](https://puu.sh/tkTs9/25f46d725b.png)

**Comment by cbettinger** [comment]
Sieht gut aus.

Hast du den Fehler gefunden, weswegen du beim Mal keine Verspätungszeiten vom Dienst zurück bekommen hast?

Was ist noch zu tun?

**Comment by geht** [comment]
> Hast du den Fehler gefunden, weswegen du beim Mal keine Verspätungszeiten vom Dienst zurück bekommen hast?

Ich habe diesbezüglich Herrn Müller vom VRN angeschrieben. Er konnte mir da leider auch nicht weiterhelfen und hat mir lediglich nochmal eine Beispielanfrage geschickt.

> Was ist noch zu tun?

Also abgesehen davon, dass mir der Dienst halt keine estimated time / Echtzeitinformation für die Haltestellen der Hochschule liefert, würde ich den Busfahrplan ansonsten soweit als fertig betrachten.

**Comment by cbettinger** [comment]
Bekommst du in diesen Fällen eine Antwort mit dem Wert 0 zurück oder ist dieses Information gar nicht strukturell in der Antwort erhalten? Vielleicht haben diese Busse einfach keine Verspätung?

**Comment by geht** [comment]
Innerhalb der Antwort gibt es für die Fahrten immer folgendes XML-Element für die geplante Abfahrtszeit:

`<TimetabledTime>2017-01-13T18:00:00</TimetabledTime>`

Eigentlich sollte es auch noch folgendes XML-Element für die voraussichtliche Abfahrtszeit geben:

`<EstimatedTime>2017-01-13T18:02:00</EstimatedTime>`

Hat ein Bus keine Verspätung, so steht in beiden Elementen der gleiche TimeStamp. Hat der Bus Verspätung, so steht im `<EstimatedTime>`-Element die voraussichtliche Abfahrtszeit.

In der Antwort auf die Anfrage für die Hochschule fehlen die entsrpechenden  `<EstimatedTime>`-Elemente, sie sind dort in der Antwort komplett nicht enthalten.
In der  Antwort auf die Anfrage für die Bitburger Straße sind diese jedoch vorhanden, manchmal eben mit den gleichen Werten wie in den `<TimetabledTime>`-Elementen, manchmal mit unterschiedlichen.

Dieser Unterschied in den Antworten ist verwunderlich, da die Anfragen, die zum Dienst hingesendet werden, komplett gleich aufgebaut sind. Der einzige Unterschied besteht darin, dass verschiedene Haltestellen (`<StopPointRef>`-Element) angefragt werden.

Für die Hochschule sieht die Zeile so aus:
`<StopPointRef>de:7211:3106</StopPointRef>`

und für die Bitburger Straße so:
`<StopPointRef>de:7211:3101</StopPointRef>`

abgesehen davon sind die Anfragen komplett gleich aufgebaut (siehe: [BusParser.cs](https://github.com/HundertTage/App/blob/feature/BusSchedule/App100Tage.PCL/Model/Bus/BusParser.cs)). Warum der Dienst strukturell unterschiedliche Antworten zu diesen Anfragen liefert ist mir unklar.

**Comment by cbettinger** [comment]
Ok, ich verstehe. Ich würde in diesem Fall dazu neigen, das Verspätungslabel vollständig zu entfernen - auch wenn wir die Daten haben. Schlimmstenfalls steht jemand zu früh an der Bushaltestelle.

Was meinst du?

**Comment by geht** [comment]
Für die Konsistenz wäre es natürlich sinnvoller entweder für alle oder für gar keine Busfahrten Verspätungen anzuzeigen.

Für die Benutzer halte ich es eigentlich schon für sinnvoll zumindest die Verspätungen anzuzeigen, die vorliegen. So würden wir ihnen diese Informationen nicht vorenthalten.

Für mich wäre beides ok. Allerdings wäre es noch eine Überlegung wert, ob man die Labels anders anordnen sollte, wenn nun gar keine Verspätungen mehr angezeigt werden sollen. Dann könnte man das Ganze vielleicht noch ein wenig kompakter gestalten.

**Comment by cbettinger** [comment]
Gut, dann lassen wir die Verspätung drin.

Was die Labels angeht: Mach mal einen Vorschlag.

**Comment by geht** [comment]
Man könnte die Linie vielleicht mit ins oberste Label hineinziehen, dann würde man sich eine Zeile sparen.
Auf den Bussen ist die Anzeige ja immer so gestaltet: "Liniennummer Ziel" (Bsp. "12 Hochschule"). Das könnte man hier auch so gestalten.

**Comment by cbettinger** [comment]
In Ordnung - so machen wir es.

**Comment by geht** [comment]
Screenshots:

![](https://puu.sh/toe8M/91d0f26b83.png)

![](https://puu.sh/toe7t/28cb805250.png)

![](https://puu.sh/toe6s/cab45304be.png)

**Comment by cbettinger** [comment]
Sehr schön. Ist noch etwas zu tun? Falls nicht, schließen.

**Comment by geht** [comment]
Gut, wird in den develop gemerged.
