### ISSUE TITLE
Absturz im Zusammenhang mit den Sticky List Headers

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#70]
![screenshot 2016-11-30 13 42 05](https://cloud.githubusercontent.com/assets/18167176/20753886/bf0b75f4-b708-11e6-9329-cf91dae8dc5f.png)

**Comment by geht** [comment]
Die Exception tritt sporadisch beim ersten Start der App auf, gerade wenn man das Tutorial geschlossen hat und die App versucht den Kalender zu laden. 

![](http://puu.sh/tVjOe/1d76c3fdf8.png)

Die StickyListHeaders-ListView, bzw. deren Adapter bezieht die Daten aus den FilteredEvents des CalenderViewmodel. Diese FilteredEvents-Collection wird bei mehreren Gelegenheiten vom CalenderViewmodel modifiziert (z.B. jedes Mal, wenn sich die AllEvents-Collection oder die CategoryFilters-Colletcion ändert).

Eventuell lässt sich die Exception dadurch lösen, dass diese Modifikationen explizit auf dem UI-Thread durchgeführt werden. Diese finden in der `FilterEvents()`-Methode des CalenderViemodel statt. `notifyDataSetChanged()` wird bereits auf dem Adapter (durch deren Basisklasse) aufgerufen.

Diesen Lösungsansatz bin ich gerade am testen. Ob das das Problem tatsächlich löst, lässt sich zzt. noch schlecht sagen, da diese Exception nur recht sporadisch ausgelöst wird.

Beim Testen ist mir allerdings aufgefallen, dass die `FilterEvents()`-Methode sehr oft aufgerufen wird.
Ich habe mal mit einem Zähler mitverfolgt, wie oft sie aufgerufen wird und folgendes hat sich dabei herausgestellt:

Ausgabe nach dem erstem Laden des Kalenders: `FilterEvents() got called 159 times now!`
Ausgabe nachdem ich auf "Aktualisieren" gedrückt habe: `FilterEvents() got called 285 times now!`

Das geht konsequent so weiter. Alleine diese eine Methode wird bei einmal Aktualisieren 126 mal aufgerufen. Und das bewirkt auch jedes Mal wieder ein `notifyDataSetChanged()` auf dem Adapter. Bei Gelegenheit sollte überprüft werden, ob sich das reduzieren lässt.

**Comment by cbettinger** [comment]
Ja, bitte :)

**Comment by geht** [comment]
Ich habe die potenzielle Lösung zu der Exception mit commit 6824c6aa5f5c475a74f4ac0f434cef977242dca3 gepusht. Bisher ist die Exception nicht erneut aufgetreten, ob das so bleibt wird sich noch herausstellen.

Des Weiteren habe ich mit commit 86c79b22784a4ed3ef1860de3687eb22a8aa6fd9 die Aufrufe der `FilterEvents()`-Methode signifikant reduziert.
Sie wurde jedes Mal aufgerufen, wenn sich an der Event-Collection etwas geändert hat (also bei jedem insert, remove, etc). Jetzt wird sie _einmal_ aufgerufen, nachdem die Collection befüllt wurde. Das hat einen Großteil der Aufrufe ausgemacht.
Zusätzlich wurde sie bei jeder Änderung an den Einstellungen (Studiengang, Startsemester, ...) aufgerufen. Jetzt wird sie nur noch aufgerufen, wenn der Fachbereich und der Studiengang geändert wird.
Eine Änderung der StudIP-URL bewirkt sowieso, dass die Collection neu befüllt wird und somit auch wieder die Filterung der Events.
Das An- und Abschalten der Kategorien wurde so belassen wie es ist und verhält sich wie gewohnt.

**Comment by Seppo007** [comment]
Android scrollt nach deiner Anpassung nicht mehr zum aktuellsten Eintrag beim Starten der App oder beim Aktualisieren, glaube das hing als Listener mit an der Collection-Änderung

**Comment by geht** [comment]
> Android scrollt nach deiner Anpassung nicht mehr zum aktuellsten Eintrag beim Starten der App oder beim Aktualisieren, glaube das hing als Listener mit an der Collection-Änderung

Wurde netterweise von @Seppo007 in commit d0c2988256d8339559fee77a7e329b8321952e98 gefixt.
