### ISSUE TITLE
Icon vor Fachbereichs-Label in Event-Detailansicht anpassen

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#72]
In der Event-Detailansicht wird vor dem Label mit dem Fachbereich das alte Hochschullogo als Icon eingesetzt:

![wp_ss_20160912_0002](https://cloud.githubusercontent.com/assets/18167176/20917926/96e858ae-bb94-11e6-9691-e5beb793c13e.png)

Aufgrund des neuen Corporate Designs und des neuen Logos der Hochschule muss dieses ersetzt werden. Das neue Logo eignet sich aufgrund des Formats nicht gut dafür. Wir müssen hier nach einem sinnvollen Ersatz suchen.

**Comment by Seppo007** [comment]
Fehlerhafter Referenzeintrag auf Issues 70 statt 72 -->
b9b103dcc3e062587e64158c1cfce6bfb6bed964

**Comment by Seppo007** [comment]
Die hier [https://github.com/HundertTage/App/issues/72#issuecomment-267719631](url) wurden angepasst, sie repräsentieren nun das finale Aussehen

**Comment by cbettinger** [comment]
Die möglichen Werte für dieses Feld sind serverseitig in der Datenbank hinterlegt. Bisher war es so, dass eine Ausweitung auf andere Fachbereiche ohne Update der App möglich war. Dieses Verhalten wird durch diese Anpassung nun gebrochen.

Es gibt zwei Möglichkeiten:
- Wir definieren ein Icon (z.B. jenes für den Wert "ALL") als Fallback für alle Werte, für die kein eigenes Icon hinterlegt wurde.
- Wir geben die Idee von fachbereichspezifischen Icons auf und nutzen ausschließlich das Icon für "ALL".

Ich muss zugeben, dass mir die zweite Idee immer noch besser gefällt.

**Comment by LokiMidgard** [comment]
Könnte nicht auch der Server das Icon zusammen mit den Strings für den fachbreich übermitteln. (Bzw. eine URL wo das Icon auf dem Server liegt)

**Comment by cbettinger** [comment]
Sind das tatsächlich exakt gleiche Icons auf allen Endgeräten, d.h. haben sie gleiche Abmessungen? Ich würde ungerne den Aufwand betreiben, mehrere Icons in drei Abmessungen verwalten zu müssen?

Nur als Hintergrundinformation: Das 100 Tage-Notebook und die 100 Tage-App sollen im kommenden Semester für alle Fachbereiche am Schneidershof zugänglich gemacht werden. Es müssten also noch weitere Icons gefunden werden.

**Comment by Seppo007** [comment]
Nein, für Android müssen für alle Auflösungen die Icons händisch angepasst werden. Für Windows Phone müssen die svg Daten so überführt werden, dass diese von einem canvas Element aufgenommen werden können.

Alphakanal Eigenschaften und müssen für jedes Icon ebenfalls angepasst werden.

Das ganze ist ziemlich aufwendig und hat viel Zeit gekostet ich würde daher beim nächsten Treffen genau besprechen ob wir bei einem Logo bleiben oder weitere einfügen wollen.

**Comment by cbettinger** [comment]
Da die Events ohnehin gefiltert werden, darf ein Nutzer alle Events besuchen, die er sieht. Daher ist die Anzeige des Feldes unnötig. Wir haben uns darauf geeinigt, dieses Feld nicht anzuzeigen.

**Comment by Seppo007** [comment]
Alle Icon-Assets wurden im Projekt für alle Plattformen entfernt.
Entsprechend wurden die Zeilen im Code gestrichen, die mit den Icons in Verbindung standen.

**Android:**
![androidicons](https://cloud.githubusercontent.com/assets/5859802/21753494/ed873166-d5ee-11e6-8036-6630bc9f59e1.png)

**iOS:**
![iosicons](https://cloud.githubusercontent.com/assets/5859802/21753496/eff3abf0-d5ee-11e6-8148-6cd90a3d2f85.png)

**Windows Phone:**
![wpicons](https://cloud.githubusercontent.com/assets/5859802/21753497/f1b06f0a-d5ee-11e6-93c6-e220296c0c8d.png)

**Comment by cbettinger** [comment]
Supi!
