### ISSUE TITLE
WP: Stadplan kann nicht angezeigt werden

### ISSUE THREAD

**Issue by geht** [HundertTage/App#76]
Ich habe gerade mal die App aus dem Store heruntergeladen (auf dem Lumia). Der Stadplan wird nicht mehr angezeigt.

![wp_ss_20161213_0001](https://cloud.githubusercontent.com/assets/882090/21136911/e7cffcb6-c127-11e6-9947-6cd169e93c08.png)
![wp_ss_20161213_0002](https://cloud.githubusercontent.com/assets/882090/21136917/eb2c4702-c127-11e6-9bec-d9fd0beca450.png)

Selbst wenn man auf den Knopf "Zu dieser Website wechseln (nicht empfohlen)" klickt wird nur genau die gleiche Seite neu geladen.

**Comment by cbettinger** [comment]
Kannst du mal die "Weiteren Informationen" aufrufen und diese hier posten?

**Comment by geht** [comment]
![wp_ss_20161213_0004](https://cloud.githubusercontent.com/assets/882090/21137544/3c31a35c-c12a-11e6-9dd6-5f7739f240db.png)

**Comment by cbettinger** [comment]
Der IE war schon immer Mist :)

**Comment by geht** [comment]
Das komische ist, ich hab die URL jetzt mal im Edge-Browser auf dem Telefon geöffnet. Dort geht es, in der App aber nicht.

**Comment by geht** [comment]
Ich habe mal auf einen separaten branch einen hotfix eingepflegt, der die https uri in eine http uri umbaut.
Das ist zwar etwas unschön, würde das Problem aber lösen.

![wp_ss_20161213_0005](https://cloud.githubusercontent.com/assets/882090/21139100/99f6d3de-c131-11e6-8ff8-da20fb322d0d.png)

**Comment by cbettinger** [comment]
Spricht etwas dagegen, das Issue zu schließen?

**Comment by geht** [comment]
> Spricht etwas dagegen, das Issue zu schließen?

Das Issue kann geschlossen werden. Der Hotfix liegt auf seinem eigenen Branch, falls wir ihn doch noch benötigen sollten.
