### ISSUE TITLE
Standard-View für Mensaplan falls Mensa-XML leer

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#77]

**Comment by geht** [comment]
Wenn der Tagesplan leer ist, ist das Verhalten bisher so, dass die Mahlzeiten des nächsten verfügbaren Tages angezeigt werden. Beispielsweise würde am Wochenende im Tagesplan also dann der Montag angezeigt werden (falls Daten entsprechend vorhanden).

Soll in einem solchen Fall dann eher angezeigt werden, dass die Mensa geschlossen ist?
Oder soll diese Info nur angezeigt werden, wenn es tatsächlich keinerlei Essensvorhersage gibt (sprich, keinerlei Daten zum anzeigen da sind)?

**Comment by cbettinger** [comment]
Der Standardtext soll nur angezeigt werden, falls die XML tatsächlich keine relevanten Daten enthält. Anderenfalls soll der jeweils nächste Tag angezeigt werden.

Der Standardtext soll lauten: "Zur Zeit liegt kein aktueller Mensaplan vor."

**Comment by geht** [comment]
Ich habe folgende Änderungen am MensaViewmodel vorgenommen (5e4c500d79b17a57904401914fc4e44df03613e5):

Sollten komischerweise noch Mahlzeiten von vergangenen Tagen in der XML sein (noch nicht aufgetreten, aber wer weiß...), so werden diese nun nicht mehr im Wochenplan angezeigt (Tagesplan wäre davon sowieso nicht betroffen).

Des Weiteren werden jetzt Öffnungszeiten im Tagesplan beachtet. Vor 13:45 Uhr wird ganz normal angezeigt, was es am heutigen Tag zu essen gibt. Nach 13:45 Uhr werden dann bereits die Mahlzeiten des Folgetages angezeigt.

**Comment by geht** [comment]
View auf dem WinowsPhone:

![wp_ss_20161221_0001](https://cloud.githubusercontent.com/assets/882090/21268559/9e11f900-c3af-11e6-9734-d34c8f3188a5.png)

**Comment by geht** [comment]
View auf Android:

![screenshot_20161223-183837](https://cloud.githubusercontent.com/assets/882090/21272345/1b599a58-c3bf-11e6-81cf-44840c0657d4.png)

**Comment by geht** [comment]
View auf iOS:

![ss 2016-12-20 at 12 10 09](https://cloud.githubusercontent.com/assets/882090/21348530/de1d12c2-c6ad-11e6-8905-118459ac86e8.png)

**Comment by cbettinger** [comment]
Uhrzeit, zu der auf den Tagesplan des jeweils nächsten Tages gewechselt wird, auf Thekenschlusszeit der Cafeteria setzen.

**Comment by geht** [comment]
> Uhrzeit, zu der auf den Tagesplan des jeweils nächsten Tages gewechselt wird, auf Thekenschlusszeit der Cafeteria setzen.

Öffnungszeiten der Cafeteria:

![](http://puu.sh/tgmJS/55bab0baee.png)

Ich habe 16:15 Uhr als Schwelle übernommen.

**Comment by cbettinger** [comment]
Supi!
