### ISSUE TITLE
"Aktualisieren" soll nur die aktuelle Funktion aktualsieren.

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#79]

**Comment by Seppo007** [comment]
Windows Phone wurde bereits vor dem letzten Release hingehend des Issues optimiert, sodass der Aktualisieren-Button im entsprechenden Pivot-Item nur die Daten die mit diesem verknüpft sind aktualisiert.

**Comment by Seppo007** [comment]
iOS hat ebenfalls separierte Aktualisierungs-Methoden je View

**Comment by cbettinger** [comment]
Und Android?

**Comment by Seppo007** [comment]
Android ebenso, es wird nur das entsprechende Fragment aktualisiert
