### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#80]
![screenshot 2016-12-14 14 18 53](https://cloud.githubusercontent.com/assets/18167176/21184840/9666a28e-c20e-11e6-9d4c-2f0facef8fc3.png)

**Comment by Seppo007** [comment]
Dieser Fehler tritt nur äußerst selten auf und ist der notwendigen Verwendung der Suport-Library geschuldet (Hier explizit die V4 im NavigationDrawerFragment). Er ist dadurch bedingt, dass beim Wechsel eines Fragments zu einem anderen Fragment der Commit zum Wechsel nach einem onInstanceSave des Fragments ausgeführt wird. Dadurch geht dieser Commit in den Shared-Preferences verloren, wodurch das Programm einen State-Loss erkennt.

Die Exception wurde umgangen, indem ein UI-State-Loss beim Fragmentwechsel akzeptiert wird. Dies hat im seltenen Fall eines State-Losses lediglich die Folge, dass in den Shared-Preferences des NavigationDrawerFragments die zuletzt ausgewählte Anzeige auf index 0, also den Kalender gesetzt wird.
