### ISSUE TITLE
iCal Parser

### ISSUE THREAD

**Issue by LokiMidgard** [HundertTage/App#81]
Hi,

@gordonwatts welcher die iCal Parser Bibliothek geschrieben hat die ich genutzt habe hat meinen pull request von damals (Unterstützung von mehr Plattformen gordonwatts/iCal.PCL#2 ) gemerged. Bis auf die Xamarin Plattform, da er diese nicht installiert hat.

Er fragte mich ob Xamarin benötigt wird. Daher wollte ich vorher nachhören ob ihr die Bibliothek noch weiterhin verwenden werdet, oder ob StudIP inzwischen obsolet ist und die Funktion in den nächsten Monaten raus fliegt.

**Comment by cbettinger** [comment]
Bis auf weiteres wird Stud.IP weiter genutzt und die Anbindung bleibt in der App.
