### ISSUE TITLE
Anzeigeprobleme nach Anpassung des Mensaplans mit Schließzeiten

### ISSUE THREAD

**Issue by Seppo007** [HundertTage/App#85]
Seitdem im Mensaplan eine Möglichkeit eingerichtet wurde, den Schließzustand der Mensa anzuzeigen, gibt es diverse Probleme in der Darstellung der ListView, wenn über VPN / eine sehr langsame Verbindung die App gestartet wird.

Dieser Fehler äußert sich darin, dass nach Öffnen der Anwendung - mit langsamer Leitung - und anschließendem Navigieren zum Mensaplan, dieser sich trotz gecachten Daten in einem Ladevorgang befindet.

Am oberen Rand wird lediglich kurzzeitig das Label angezeigt, dass die Mensa gerade geschlossen wäre. Nach Vollendung des Ladevorgangs bleibt die gesamte Ansicht des Fragments weiß. Wischt man nun nach unten, so sind die aktuellen Speisen wieder sichtbar, allerdings verbleibt am oberen Rand eine weißer Balken mit der selben Höhe, die auch das angesprochene Label hat.

Wechselt man nun zu irgendeinem anderen Fragment der Anwendung werden keine Views mehr angezeigt, sodass die Anzeige weiß bleibt.

**Ablauf:**
![screenshot_20170112-170510](https://cloud.githubusercontent.com/assets/5859802/21898070/d89bc9d8-d8eb-11e6-8961-129fc1a33c4e.png)
![screenshot_20170112-170519](https://cloud.githubusercontent.com/assets/5859802/21898073/daabb152-d8eb-11e6-9bc4-76422cb1a78d.png)
![screenshot_20170112-170524](https://cloud.githubusercontent.com/assets/5859802/21898074/dc50484c-d8eb-11e6-994f-73bb003d73d9.png)
![screenshot_20170112-171512](https://cloud.githubusercontent.com/assets/5859802/21898076/de5f7194-d8eb-11e6-83f1-dc17a937ef04.png)
![screenshot_20170112-171516](https://cloud.githubusercontent.com/assets/5859802/21898079/e11d06f8-d8eb-11e6-9843-47c645c0b7fe.png)

**Comment by geht** [comment]
Der Fehler konnte erfolgreich reproduziert werden und wurde mit commit 0cc9b4f12d1ae0c0f62c9515ebe857685b522cd2 behoben.

Das Problem war, dass während der Mensaplan noch geladen wurde, bzw. während der Anzeige des Update-Dialogs, das Fragment im Hintergrund durch den PropertyChangedListener verändert wurde, da sich durch das Laden der Daten der Zustand des MensaClosed-Properties geändert hat.
