### ISSUE TITLE
Aktualisierung der Tutorial-Screenshots

### ISSUE THREAD

**Issue by Seppo007** [HundertTage/App#88]
Die angezeigten Screenshots im Tutorial müssen an die neue Version der App angepasst werden.

- Busfahrplan
- Neue Push-Notifications mit ActionButtons (sobald implementiert)
- Mensa (Bilder / Tag- & Wochenwechsel)

**Comment by cbettinger** [comment]
Erledigt in 57cd69b, 8e51136 und c42f2a9.
