### ISSUE TITLE
Allgemeine Anmerkungen zu den Veranstaltungen ("Kleingedrucktes") in der App darstellen

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#92]
Die auf der Webseite dargestellten Anmerkungen zu

a) den Veranstaltungen in der Einführungswoche
b) den Veranstaltungen im Laufe des Semesters

sollen in geeigneter Weise dargestellt werden.

Da die beiden Texte sich durchaus ändern können, wäre es vermutlich geschickt, diese nicht hart zu kodieren.

**Comment by cbettinger** [comment]
Überlege dir bitte mal, wie und wo man das am besten einbaut.

**Comment by geht** [comment]
Es gäbe verschiedene Orte, wo man die Anmerkungen einbauen könnte. Mir sind jetzt erst einmal die folgenden Varianten eingefallen:

1. Als letzte Seite im Tutorial, könnte als Bild (evtl. nicht so toll bzgl. Änderbarkeit) oder (wahrscheinlich) auch als eine Art TextView umgesetzt werden. 
2. Als zweite Ansicht oder Informationsdialog im Kontextmenü des Kalenders.
3. Als weiteren Hauptmenüpunkt, inkl. entsprechendem View.

Für die Datenhaltung (sprich, wo sind die Texte gespeichert) sind mir die folgenden Varianten eingefallen:
1. Als Konstante einer entsprechenden Klasse im Model.
2. Als String in der strings.txt.
3. Als (Text-)Datei, die auf dem SmartPhone abgelegt ist (muss dann entsprechend ausgelesen werden).
4. Auf der Datenbank des 100 Tage-Servers (muss dann entsprechend abgerufen werden).

**Comment by cbettinger** [comment]
Zur Ablage des Strings ist die Datenbank zwar der aufwändigste, aber vermutlich der beste Weg. Ich habe Sorge, dass dieser Text in Zukunft häufiger angepasst werden muss und dann jedesmal (nur dafür) einen Release anzustoßen, wäre lästig.

**Comment by cbettinger** [comment]
Zur Anzeige der Texte: So richtig gut gefällt mir das alles nicht. Im Tutorial will man keine langen Texte lesen, sondern mit der App loslegen. Hauptmenüeintrag ist mir zu prominent. Am besten ist vielleicht noch der Kontextmenüeintrag im Kalender. Da besteht eben nur die Gefahren, dass sich das niemand anschaut.

**Comment by geht** [comment]
> Da besteht eben nur die Gefahren, dass sich das niemand anschaut.

Für die Darstellung dieser Informationen im Kalender sind mir noch folgende Varianten eingefallen. Darstellung der Anmerkungen

1. noch vor/über der eigentlichen Liste. Dann würden die Anmerkungen zu Anfang des Semesters auf jeden Fall gesehen werden.
2. nach/hinter der eigentlichen Liste. Dann würde man sie halt auch nur sehen, wenn man ganz runter scrollt.
3. teils teils wäre natürlich auch möglich
4. über das Kontextmenü, wie bereits vorher gesagt. Das könnte man noch damit verbinden, die Anmerkungen explizit anzuzeigen, wenn der Kalender das aller erste Mal geöffnet wird, ähnlich wie auch das Tutorial beim aller ersten Start der App angezeigt wird und danach nach Belieben eingesehen werden kann.



> Zur Ablage des Strings ist die Datenbank zwar der aufwändigste, aber vermutlich der beste Weg. Ich habe Sorge, dass dieser Text in Zukunft häufiger angepasst werden muss und dann jedesmal (nur dafür) einen Release anzustoßen, wäre lästig.

Man könnte natürlich auch eine (Text-)Datei über den 100 Tage-Server direkt bereitstellen. Dann müsste sogar nur diese Datei ausgetauscht werden, wenn sich dort etwas ändert, anstatt die Änderung nochmal in die Datenbank einpflegen zu müssen.

Die Variante mit der Datenhaltung in der Datenbank wäre aber wahrscheinlich am konsistentesten und am sichersten bezüglich Schreib- und Lesezugriffe.

**Comment by cbettinger** [comment]
Bitte packe den Text in eine neue View, die über das Kontextmenü des Kalenders aufgerufen werden kann.
Der Text soll in einer txt-Datei auf dem Server abgelegt werden, der den Inhalt über einen neuen Handler ausliefert.

**Comment by geht** [comment]
Kleines Update zum aktuellen Zwischenstand:

Auf dem Server wurde ein entsprechender Handler eingeführt (siehe https://github.com/HundertTage/Server/commit/7640434a978a238b622ada5d58041515e7f56e25).

Und auf der Clientseite habe ich den PCL-Teil umgesetzt (siehe 51bc179c44b65f0e4cb043c1d4b0635810587c9a), sowie die Implementierung für das WindowsPhone (siehe d1f13c5641e200ed4a3d735665dded7258ac8263).

Hier ein paar Screenshots
![wp_ss_20170414_0001](https://cloud.githubusercontent.com/assets/882090/25044504/4e738a0a-2127-11e7-8a8b-ab86ef9d424f.png)
Aus irgendeinem Grund ist das Kontextmenü hier größer/höher, als es sein sollte. Der Grund ist noch unbekannt, ich werde das noch überprüfen.

![wp_ss_20170414_0004](https://cloud.githubusercontent.com/assets/882090/25044650/097013a0-2128-11e7-9037-73d91a7dd6cd.png)
Das wird angezeigt, wenn die Anmerkungen nicht heruntergeladen werden konnten.

![wp_ss_20170414_0002](https://cloud.githubusercontent.com/assets/882090/25044505/50d338b8-2127-11e7-85c2-a4dfc105f460.png)
Der TextBlock wird horizontal gewrappt und ist vertical scrollbar.

![wp_ss_20170414_0003](https://cloud.githubusercontent.com/assets/882090/25044509/52893d38-2127-11e7-9975-4fc0989ea959.png)

**Comment by cbettinger** [comment]
Supi. Du kannst den Menüeintrag (wie auf der Webseite) ruhig "Das Kleingedruckte" nennen. Das erregt vielleicht etwas mehr Aufmerksamkeit als "Anmerkungen".

**Comment by geht** [comment]
> Du kannst den Menüeintrag (wie auf der Webseite) ruhig "Das Kleingedruckte" nennen.

Ich habe das für die gesamten Texte übernommen und die Strings.txt entsprechend angepasst (siehe c00ae66887368afc8770dd40b7796601dddfba3e).
Für Windows Phone habe ich die Größe der (neuen) Überschrift angepasst, damit diese noch in eine Zeile passt.

Die Implementierung für Android wurde nun umgesetzt (siehe 2b34b40bf394adbbc03351652d9aaff2b73a4c97).

Hier ein paar Screenshots:
![01](https://cloud.githubusercontent.com/assets/882090/25175858/9a8d2634-24fc-11e7-986f-3a37c2eb656c.png)

![02](https://cloud.githubusercontent.com/assets/882090/25175860/9c9fa604-24fc-11e7-9d90-fc7e8b251869.png)

![03](https://cloud.githubusercontent.com/assets/882090/25175862/9e9796d8-24fc-11e7-925c-ef83ace4391f.png)

![04](https://cloud.githubusercontent.com/assets/882090/25175865/a0ca691c-24fc-11e7-80ae-c6b161dfc45c.png)

**Comment by geht** [comment]
Die Implementierung für iOS wurde nun umgesetzt (siehe cf83258923af978ab8939094d7c1ab7f2be47390 und e6f371b7d9df92e0a87ab8058b6276b6b6757aef).

Hier ein paar Screenshots:
![0](https://cloud.githubusercontent.com/assets/882090/25525627/23e4fe06-2c10-11e7-9316-6ace5cce9d47.jpg)

![1](https://cloud.githubusercontent.com/assets/882090/25525630/255041f6-2c10-11e7-8edb-1d05c9a57fce.png)

![2](https://cloud.githubusercontent.com/assets/882090/25525631/271709b6-2c10-11e7-8c7c-2be812a81d6f.png)

![3](https://cloud.githubusercontent.com/assets/882090/25525634/28f2eb2e-2c10-11e7-8c7c-e6cf0c70976d.png)

**Comment by geht** [comment]
Zu der Höhe des Kontextmenüs beim WindowsPhone:
Ich habe mal alternativ zur Erstellung der ApplicationBarMenuItems über die xaml-Page diese einmal komplett programmatisch anlegen und in die ApplicationBar einfügen lassen (wie auch im MSDN beschrieben: https://msdn.microsoft.com/de-de/library/windows/apps/ff431813(v=vs.105).aspx), aber das hat auch keinen Unterschied gemacht.

Man hat keinerlei Zugriff auf die Höhe der angezeigten Liste und auch keinerlei Stellschrauben, mit der sich die Höhe ändern lässt, außer durch die Anzahl der ApplicationBarMenuItems.

Die Best Practices empfehlen nicht mehr als fünf MenuItems einzufügen, da der Benutzer sonst durch die Liste scrollen muss. Hier ein Screenshot, bei dem ich das mal getestet habe:

![wp_ss_20170428_0002](https://cloud.githubusercontent.com/assets/882090/25563526/c9731b76-2d9d-11e7-9db5-8b6fe6d7c7b9.png)

In unserem Fall haben wir zwar nur vier MenuItems (was weniger ist als die Empfehlung vorgibt), die Höhe der Liste entspricht aber schon der Maximalgröße. Eine Scrollbar ist dort allerdings nicht vorhanden, es ist lediglich die Höhe, die nicht passt. Würde man wieder ein MenuItem entfernen, wäre die Höhe wieder passend.

**Comment by geht** [comment]
Ich habe den Margin beim WindowsPhone nochmal angepasst (commit bd6370fe70e378223fb9a3eeb87e34595f5e6336)

![ss 2017-05-03 at 12 42 45](https://cloud.githubusercontent.com/assets/882090/25657586/e4e638e4-2ffe-11e7-8114-accdfa8406d6.png)
