### ISSUE TITLE
Icon ändern

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#93]
An allen Stellen in der App und in den Stores soll das "alte" 100 Tage-Projektlogo (das mit den Balken) verwendet werden.

Das hatten wir zwischenzeitlich durch eine Variante ohne Balken ersetzt, da es durch die automatisch Abrundung von Icons in der iOS-Variante bescheiden aussah (kein Whitespace, Balken enden am Rand des Icons).

Wir müssen also das eigentliche 100 Tage-Logo mit extra Whitespace versehen, damit es durch diesen Beschnitt nicht wieder zum gleichen Effekt kommt.

**Comment by geht** [comment]
Das neue Icon wurde auf allen Plattformen wieder durch das alte ersetzt
(Sowohl App-Icons, als auch Splashscreen-Icons).
iOS erhält noch eine angepasste Variante.

Android
![screenshot_20170404-155243](https://cloud.githubusercontent.com/assets/882090/24660459/e10d796e-194f-11e7-91cd-b07e2c2dcfff.png)
![screenshot_20170404-155303](https://cloud.githubusercontent.com/assets/882090/24660466/e3ea13c2-194f-11e7-9aba-9e19bda9efca.png)

iOS
![ss 2017-04-04 at 03 50 06](https://cloud.githubusercontent.com/assets/882090/24660475/e986a4bc-194f-11e7-83f1-868ab7413186.png)
![ss 2017-04-04 at 03 50 30](https://cloud.githubusercontent.com/assets/882090/24660484/ec2960ba-194f-11e7-8874-e1a145e5a40c.png)

Windows Phone (Emulator zeigt den Splashscreen nicht an, die Bilder wurden aber wieder durch die alten ersetzt)
![ss 2017-04-04 at 03 46 52](https://cloud.githubusercontent.com/assets/882090/24660491/f2117940-194f-11e7-8af2-310f08e993f4.png)

**Comment by cbettinger** [comment]
Hast du darauf geachtet, dass die Icon-Größe dennoch die gleiche ist, wie in der Version ohne Balken?

**Comment by geht** [comment]
Es wurden die gleichen Größen eingehalten, wie in issue #60 festgehalten und umgesetzt wurden (nur halt jetzt mit dem neuen alten Logo).

**Comment by cbettinger** [comment]
Sehr gut.

**Comment by geht** [comment]
So sieht das Logo auf iOS mit 20% Rand (e10d27aad901142e84e387dbe4e85a38d24e2d99) aus:
![ss 2017-04-05 at 12 01 41](https://cloud.githubusercontent.com/assets/882090/24700551/cf41fde2-19f7-11e7-8634-caadfa487e67.png)

**Comment by cbettinger** [comment]
Sehr gut. Auch unsere Gestalterin hat grünes Licht gegeben. Du kannst das Issue schließen, wenn du soweit bist. Bitte denke daran, alle erledigten Dinge in den develop-Branch zu mergen.

**Comment by geht** [comment]
Ist in develop gemerged.
