### ISSUE TITLE
Mensaplan

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/App#99]
Das entsprechende Icon des Hauptbildschirms öffnet den bereits vorhandenen Mensaplan.

Derzeit erscheint hier eine ominöse vierte Theke ("Casa Blanca"), die zudem offensichtlich falsch interpretiert wird. Bitte prüfen und korrigieren.

**Comment by PrieDayThor** [comment]
Hab die App gerade nochmal aus dem Store geladen. 
Die besagte 4. Theke ist dort nicht vorhanden. 
Auch bei der Version aus dem Gamification-Branch ist diese Theke nicht vorhanden. 

Mit welchem Gerät ist das Problem denn aufgetreten?

**Comment by cbettinger** [comment]
Jetzt ist diese Theke tatsächlich auch bei mir nicht mehr da. Ich nehme mal an, da hat sich ein Fehler in die XML-Datei der letzten Woche eingeschlichen. Freitag nachmittags wird die XML immer austauscht.

**Comment by cbettinger** [comment]
Anscheinend ist diese Casa Blanca doch kein Fehler. Gestern (Montag) wurde auf der Mensa-Webseite diese Theke angezeigt:

![screenshot 2017-12-11 10 16 11](https://user-images.githubusercontent.com/18167176/33873620-06924704-df1c-11e7-85a1-7d5477ec05cb.png)

Hier müsste das Parsen der XML-Datei also noch mal angepasst werden.

Zusätzlich ist mir aufgefallen, dass heute (Dienstag) auf der Webseite unter Casa Blanca steht: "Die Theke ist heute geschlossen.", die aktuelle Version der App versucht dennoch, die Theke darzustellen:

![image-1](https://user-images.githubusercontent.com/18167176/33873838-d1584d94-df1c-11e7-8951-e1914f8d0a65.jpg)

**Comment by cbettinger** [comment]
Ich heute erfahren, dass die Gerichte tatsächlich "Lecker" und "Fein" heißen. Hier gibt es nichts zu tun.
